# Generated by Django 4.1.5 on 2023-02-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_description_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('DELETED', 'deleted'), ('DRAFT', 'draft'), ('ACTIVE', 'active')], max_length=10),
        ),
    ]
