# Generated by Django 4.1.5 on 2023-02-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('DELETED', 'deleted'), ('DRAFT', 'draft'), ('ACTIVE', 'active')], default='active', max_length=10),
        ),
    ]
