# Generated by Django 4.1.5 on 2023-02-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('DELETED', 'deleted'), ('DRAFT', 'draft'), ('ACTIVE', 'Active')], default='active', max_length=10),
        ),
    ]
