# Generated by Django 4.1.5 on 2023-02-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
