# Generated by Django 4.1.5 on 2023-03-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SHIPPED', 'shipped'), ('DELIVERED', 'delivered'), ('DELETED', 'deleted')], default='active', max_length=10),
        ),
    ]
