# Generated by Django 4.1.5 on 2023-03-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_vendor_email_remove_vendor_password_and_more'),
        ('store', '0023_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor'),
        ),
    ]
