# Generated by Django 4.1.5 on 2023-03-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_description_userprofile_image_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
