# Generated by Django 4.1.5 on 2023-03-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
