# Generated by Django 4.1.5 on 2023-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default=True, max_length=12),
        ),
    ]
