# Generated by Django 4.1.5 on 2023-03-13 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0002_vendor_email_vendor_password_vendor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
